language: perl
perl:
  - "5.20"
os:
  - linux

before_install:
  - git clone https://github.com/sonntagd/Dresden-pm.github.io.git repo
script:
  cd repo && perl ../converter/converter.pl
after_script:
  - git add .
  - git config --global user.email "someone@dresden.pm"
  - git config --global user.name "Dresden-pm master of html"
  - git commit -m 'automatic md to html conversion powered by travis-ci'
  - perl -MSereal::Decoder -MMIME::Base64 -MFile::Slurp -E 'write_file "id_rsa_una" => decode_sereal decode_base64($ARGV[0])' $GITHUBKEY
  - GIT_SSH=./git_ssh_wrapper.sh git push origin master
  - rm id_rsa_una
