language: perl
perl:
  - "5.20"
os:
  - linux

before_install:
  - cpanm Sereal::Decoder MIME::Base64 File::Slurp
  - perl -MSereal::Decoder -MMIME::Base64 -MFile::Slurp -E 'write_file "id_rsa_una" => decode_sereal decode_base64($ARGV[0])' $GITHUBKEY
  - chmod 600 id_rsa_una
  - mkdir repo && cd repo
  - GIT_SSH=../git_ssh_wrapper.sh git clone git@github.com:Dresden-pm/Dresden-pm.github.io.git .
  - cd ..
script:
  - cd repo && perl ../converter.pl markdown
  - git diff
  - git add *.html -v
  - git config --global user.email "someone@dresden.pm"
  - git config --global user.name "Dresden-pm master of html"
  - true git commit -m 'automatic md to html conversion powered by travis-ci'
  - GIT_SSH=../git_ssh_wrapper.sh git push origin master
after_script:
  - cd .. && rm id_rsa_una
